# -*- coding: utf-8 -*-
"""Benchmarking CI 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t1SNjMmp5_ulkxfRcGkz0qYWzCV2Siwj
"""

import spacy
import pandas as pd

nlp = spacy.load('en_core_web_sm')

with open('dialogues_text.txt', 'r') as f:
    text = [line for line in f.readlines()]
df = pd.DataFrame(text,columns=['text'])
df.head()

text = df['text']
pos_tags = []
for sentence in text:
  doc = nlp(sentence)
  pos_tag_list = [(token.text, token.pos_) for token in doc if token.pos_ == 'VERB']
  if pos_tag_list:
   pos_tags.append(pos_tag_list)

fdf = pd.DataFrame(pos_tags)
fdf.head(len(fdf))

verbs_df = fdf.dropna(axis = 'columns')
verbs_df.to_csv('verbs.csv', index=False)
print(verbs_df)